#!/bin/bash

# Script for overriding git flows.
# - do not show changes from `public` directory on `diff`
# - do not add changes from `public` on `add`, except whem explicit adding them`

if [[ "$1" == "diff" && "$@" != *"--help"* ]]; then
    shift 1
    command git diff "$@" -- :^public
elif [[ "$1" == "add" && "$@" != *"--help"* && "$@" != *"public"* ]]; then
    shift 1
    command git add "$@" -- :^public
else
    command git "$@"
fi